server:
  port: 7000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.230.162:3306/media
    username: root
    password: c2011020@
  data:
    redis:
      database: 0
      port: 6379
      host: 122.51.230.162
      password: c2011020@
      timeout: 10000

minio:
  endpoint: http://122.51.230.162:9000
  accessKey: 0wYzOSjLKxikkE9CHAW5
  secretKey: nsicCdSazmmO2nOZedpnPFdCq7uz1XDfWqCzxHDx
  bucketName: test

logging:
  config: classpath:logback/logback-prod.xml
  level:
    root: info