
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.230.162:3306/media
    username: root
    password: c2011020@
  data:
    redis:
      database: 0
      port: 6379
      host: 122.51.230.162
      password: c2011020@
      timeout: 10000
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

minio:
  endpoint: http://122.51.230.162:9000
  accessKey: 0wYzOSjLKxikkE9CHAW5
  secretKey: nsicCdSazmmO2nOZedpnPFdCq7uz1XDfWqCzxHDx
  bucketName: test

logging:
  config: classpath:logback/logback-dev.xml